### ISSUE TITLE
Package doesn't work in SvelteKit

### ISSUE THREAD

**Issue by mtayyabviz** [BernhardWebstudio/svelte-virtual-table#3]
I unable to get this package running properly within Sveltekit. I have faced following errors with my actions trying to get it worked, but still failed:
- First installed using `npm install --save-dev svelte-virtual-table`, then imported within a svelte component. I got:
	- `Cannot find module` error
- Next, I tried to resolve the npm module using `resolve` in `vite.config.ts`. It didn't work out
- Then, I dig further with `npm run build`, I got:
	- `WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.`

So, far I unable to get it worked. Any fixes you can offer?

Thank you,
Tayyab

**Comment by GenieTim** [comment]
Hi, I have now published a new version (2.0.0), which is entirely new, starting from svelte-kit. Its test-app works without problems
